/**
 * Application Constants and Enumerations
 */

const ROLES = {
  MEMBER: 'MEMBER',
  LIBRARIAN: 'LIBRARIAN',
  ADMIN: 'ADMIN'
};

const MEMBER_TYPES = {
  STUDENT: 'STUDENT',
  FACULTY: 'FACULTY',
  GENERAL: 'GENERAL'
};

const USER_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED'
};

const BOOK_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  ARCHIVED: 'ARCHIVED',
  MAINTENANCE: 'MAINTENANCE'
};

const TRANSACTION_STATUSES = {
  ACTIVE: 'ACTIVE',
  RETURNED: 'RETURNED',
  OVERDUE: 'OVERDUE',
  LOST: 'LOST',
  DAMAGED: 'DAMAGED',
  CANCELLED: 'CANCELLED'
};

const HOLD_STATUSES = {
  WAITING: 'WAITING',
  READY: 'READY',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
};

const FINE_STATUSES = {
  UNPAID: 'UNPAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  WAIVED: 'WAIVED'
};

const PAYMENT_METHODS = {
  CASH: 'CASH',
  CARD: 'CARD',
  ONLINE_SIMULATED: 'ONLINE_SIMULATED',
  WAIVED: 'WAIVED'
};

const NOTIFICATION_TYPES = {
  DUE_SOON: 'DUE_SOON',
  OVERDUE: 'OVERDUE',
  HOLD_READY: 'HOLD_READY',
  FINE_CREATED: 'FINE_CREATED',
  FINE_PAYMENT: 'FINE_PAYMENT',
  GENERAL: 'GENERAL'
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  USER_EXISTS: 'USER_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  BOOK_UNAVAILABLE: 'BOOK_UNAVAILABLE',
  BORROWING_LIMIT_REACHED: 'BORROWING_LIMIT_REACHED',
  DUPLICATE_LOAN: 'DUPLICATE_LOAN',
  UNPAID_FINES_BLOCKED: 'UNPAID_FINES_BLOCKED',
  TRANSACTION_NOT_ACTIVE: 'TRANSACTION_NOT_ACTIVE',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  DUPLICATE_HOLD: 'DUPLICATE_HOLD',
  HOLD_LIMIT_REACHED: 'HOLD_LIMIT_REACHED',
  FINE_ALREADY_PAID: 'FINE_ALREADY_PAID',
  INVALID_PAYMENT_AMOUNT: 'INVALID_PAYMENT_AMOUNT',
  EXCEEDS_OUTSTANDING_FINE: 'EXCEEDS_OUTSTANDING_FINE',
  CANNOT_DELETE_ACTIVE_BOOK: 'CANNOT_DELETE_ACTIVE_BOOK',
  INSUFFICIENT_COPIES: 'INSUFFICIENT_COPIES',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

module.exports = {
  ROLES,
  MEMBER_TYPES,
  USER_STATUSES,
  BOOK_STATUSES,
  TRANSACTION_STATUSES,
  HOLD_STATUSES,
  FINE_STATUSES,
  PAYMENT_METHODS,
  NOTIFICATION_TYPES,
  ERROR_CODES
};
